#datasource
spring:
  # datasource
  datasource:
    url: jdbc:mysql://localhost:3306/tiny_bilibili
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis
  redis:
    host: 192.168.40.10
    port: 6379
    password: 12345678

# rocketmq
rocketmq:
  name:
    server:
      address: 192.168.40.10:9876

# fastdfs
fdfs:
  tracker-list: 192.168.40.10:22122
